### PR TITLE
Adding s390x/s390-unknown-linux-gnu samples patch

### PR DESCRIPTION
**Pull request by pradghos**
- This patch will allow other vendor name to pair with s390x/s390.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Can you send this to https://github.com/conda-forge/crosstool-ng? And then update here?

**Comment by pradghos** [comment]
> 
> 
> Can you send this to https://github.com/conda-forge/crosstool-ng? And then update here?

Looks like I can't create a personal fork for conda-forge/crosstool-ng because same name repository is already exists.
Once it will merge , I will create PR https://github.com/conda-forge/crosstool-ng . For time being, I have created PR for conda-forge/crosstool-ng-feedstock#15 and added it as patch for now . I will clean it up from here later. Please let me know if you are fine.

**Comment by isuruf** [comment]
> Looks like I cant create a personal fork for conda-forge/crosstool-ng because same name repository is already exists.

You don't need to create a personal fork. You can send a PR from your already existing fork

**Comment by pradghos** [comment]
@isuruf created a PR - https://github.com/conda-forge/crosstool-ng/pull/2.  So here in `crosstool-ng-feedstock` , I have to increase the build number and request for re-render. Let me know if I missed out anything.

**Comment by isuruf** [comment]
You only have to increase the version to `1.24.0.132_gc74611b1`

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
